apiVersion: v1
kind: Service
metadata:
  labels:
    app: udaconnect-connection-api
  name: udaconnect-connection-api
spec:
  ports:
  - name: 5000-30003
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30003
  selector:
    app: udaconnect-connection-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udaconnect-connection-api
  name: udaconnect-connection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-connection-api
  strategy: {}
  template:
    metadata:
      labels:
        app: udaconnect-connection-api
    spec:
      containers:
      - image: gupta1yushi/udaconnect-connection-api:latest
        name: udaconnect-connection-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always